language: node_js
node_js: '6'
sudo: required
dist: trusty
addons:
  firefox: 52.3.0
  postgresql: '9.4'
install:
- npm install
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- psql -c 'create database bitballs;' -U postgres
script:
- sudo sh -c 'dbus-uuidgen > /etc/machine-id'
before_deploy:
- git config --global user.email "justin@bitovi.com"
- git config --global user.name "bitballs deploy bot"
- node public/build
- git add public/dist/ --force
- git commit -m "Updating build."
- node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
deploy:
  skip_cleanup: true
  provider: heroku
  app: bitballs
  api_key:
    secure: V80hhTbgVAUMvRnMATlrxvhA8ZkGzKKJ58SIdQkIvX2el3aL2pjxzDS6w9LyoLb19XLjJmS3TnDk2z5F5yi+pA9vqQMBzaEX0p0VHuwVMrc4AyoL9ltM9di/ICL70A5c2wLc/yxToeP35jHR9ZFFZs4thROc7A3VGlRKRdjmtr84jJXTnSlnDceZwANPUUK4VRkQyV3Fb9ygqvScSHW0j4XYDl4dAS6GB6iLuzQIKAT+WX1XTE7wnK6MkZL8onyQHRWIdLnHitdAhrJUssI+zLldlG9LacZwAgPnBS72ie1SDg1AZLe20zFCSFJ69WrACRR9UFqoOB4K0GX7mX9dNa6edQsYEpVeHdNpGvGOpTbhc+/NobMbOUUE+HqEtF6jG9P4Hm4s3g7xO8SLzZ46gd2hTWYm5IP/r13VKlnzCklP4YJOnanKcDOtdnZDyvhVom0s9PsvsVqo9RNEpISZRawldMVx/NeXSG5aszlbNgLOXsg1z+t0sCjCHeQqMKJZ+4lqxLSGImZR6/7f/kMijcK/jYsOYVk/Tr5G0PzB7N1PjeRoSJKVqJJK7lwBRek/YbTSUKDkWkf2AkKUAnaB51431cJs0hR15wGuAu7LjVNglticuHjped8Y3grJJoxRuQJv2ezWOq8o7Bs41ELMIgSHJA3C3YUe48Urqbpl0tQ=
env:
  global:
  - secure: T1a7ss3xIM8W1o3ceXTHl+sf+cyU5Z485Tfp+TGxL5yXzx5aeNKGvlVct4p0kBNEgbOeb/i940Lq1LFtVmqP/rRsdqW+dxV52O4QaGKZJsBbiNGCod+PdtcQFy+MNiIfM1fdLVEQcjctPi/DF4ugqHoq/0ShPQJXevVD4MFmB4ph3nCyH2zjPnokWWpFIDXTyyIHQyXq9ol9cFmHBkYdAYHd5Lo9NKpbHIjx2Fzb9qiFJq26MMBomgZT1l884TS9c9bwQHumzjJy0GZEyhNE/AReycNTEo33CkcD/OAQ7arNsU2c2/yVHVUcXUJSmIGDDbL/OC1/9tjTB/TWjMrkyxvv/5omO5pQpcdM0ed1aGjH2EBUhWlyjY5zivsyr3NlbYfeG/aLsjns6N0VDpcGtqRlvYhg2DQkjbTW4BIoDSBrxTM5k+ERnrRinI46FzPHObFt4i74o4TGlEsWTKLKnKxUhVWpfyiD2XItE7yF+Ol+guelvlYTNK/2J62aVURN5LZWKtsS98JeEOJS4TXt3d/osFxyBOFwIU/AHp09bg6sOTfaj6gZkz2n81TaezVwWR6Ly55AsACqbAWmSKO0X72OEGWDeT0kQ4CyrYV9XRRqzBpQB0EftBxAgLaUPilT7UMH7W8iU2zu06s931+KNSDdB4aUJuuSwpETWz1oQjo=
